service: sls-db-warmer-template

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-northeast-1

custom:
  dotenv:
    basePath: ./env/

plugins:
  - serverless-dotenv-plugin
  - serverless-offline
  - serverless-offline-scheduler

functions:
  warmDb:
    handler: build/handler.warmDb
    events:
      - schedule: ${file(./serverless-settings/schedules.yml):${opt:stage}.warmDb}